import Foundation

public enum BCP47Tag: String, CaseIterable {
  case ar_SA = "ar-SA"
  case cs_CZ = "cs-CZ"
  case da_DK = "da-DK"
  case de_DE = "de-DE"
  case el_GR = "el-GR"
  case en_AU = "en-AU"
  case en_GB = "en-GB"
  case en_IE = "en-IE"
  case en_US = "en-US"
  case en_ZA = "en-ZA"
  case es_ES, es_MX = "es-ES"
  case fi_FI = "fi-FI"
  case fr_CA = "fr-CA"
  case fr_FR = "fr-FR"
  case hi_IN = "hi-IN"
  case hu_HU = "hu-HU"
  case id_ID = "id-ID"
  case it_IT = "it-IT"
  case ja_JP = "ja-JP"
  case ko_KR = "ko-KR"
  case nl_BE = "nl-BE"
  case nl_NL = "nl-NL"
  case no_NO = "no-NO"
  case pl_PL = "pl-PL"
  case pt_BR = "pt-BR"
  case pt_PT = "pt-PT"
  case ro_RO = "ro-RO"
  case ru_RU = "ru-RU"
  case sk_SK = "sk-SK"
  case sv_SE = "sv-SE"
  case th_TH = "th-TH"
  case tr_TR = "tr-TR"
  case zh_CN = "zh-CN"
  case zh_HK = "zh-HK"
  case zh_TW = "zh-TW"
}
